# include and lib directories
QSSLIB_INCLUDE = $(BUILD_DIR)/include
QSSLIB_DIRS = -L$(BUILD_DIR)/lib/ 
QSSLIB_LIBS    = -llsmpqs -lm
OPTIM_FLAGS = -O3 -funroll-loops -fPIC
QSSLIB_BIN_DIR = $(BUILD_DIR)/bin/
OMP_FLAGS = -fopenmp

# Pattern Rules
%.o: %.c
	gcc -c $(OPTIM_FLAGS) -I$(QSSLIB_INCLUDE) -o $@ $< $(OMP_FLAGS)

%.o: %.c %.h
	gcc -c $(OPTIM_FLAGS) -I$(QSSLIB_INCLUDE) -o $@ $< $(OMP_FLAGS)

%.o: %.f
	gfortran -c $(OPTIM_FLAGS) $(FFLAGS) $(FFLAGS_EXTRA) -o $@ $< $(OMP_FLAGS)
	
%.o: %.cc
	g++ -c -O3 -funroll-loops -fPIC -fno-implicit-templates  -I$(QSSLIB_INCLUDE) -o $@ $<

%.o: %.cc %.h
	g++ -c -O3 -funroll-loops -fPIC -fno-implicit-templates  -I$(QSSLIB_INCLUDE) -o $@ $<

%.o: %.cpp %.h
	g++ -c -O3 -funroll-loops -fPIC -fno-implicit-templates  -I$(QSSLIB_INCLUDE) -o $@ $<
